"""
Automatically generated by scripts from the changes in raw_data/models.
"""
from __future__ import annotations
import logging
from typing import TypedDict, Unpack, Literal, Self
from dataclasses import dataclass, field, replace
import polars as pl
import dataframely as dy
import pandapower as pp
import openpyxl
from .switch import Switch
from .bus import Bus
from .line import Line
from .ext_grid import ExtGrid
from .load import Load
from .trafo import Trafo
from .sgen import Sgen


all_models: dict[str, dy.Schema]  = dict(
    switch=Switch,
    bus=Bus,
    line=Line,
    ext_grid=ExtGrid,
    load=Load,
    trafo=Trafo,
    sgen=Sgen
) # type: ignore

class PandaPowerDataFrame(TypedDict, total=False):
    trafo3w: pl.DataFrame
    switch: pl.DataFrame
    bus: pl.DataFrame
    line: pl.DataFrame
    ext_grid: pl.DataFrame
    load: pl.DataFrame
    gen: pl.DataFrame
    trafo: pl.DataFrame
    sgen: pl.DataFrame

def validate(**kwargs: Unpack[PandaPowerDataFrame]) -> None:
    for table, df in kwargs.items():
        try:
            all_models[table].validate(df)  # type: ignore
            
        except dy.exc.ValidationError : # type: ignore
            _, failure = all_models[table].filter(df) # type: ignore
        
            raise ValueError(
                f"\n\n\nValidation failed for table {table} with error: {failure.invalid()}"
            )

@dataclass(frozen=True)
class PandaPowerImporter:
    switch: dy.DataFrame[Switch] = field(
        default_factory=lambda: Switch.create_empty()
    )
    bus: dy.DataFrame[Bus] = field(
        default_factory=lambda: Bus.create_empty()
    )
    line: dy.DataFrame[Line] = field(
        default_factory=lambda: Line.create_empty()
    )
    ext_grid: dy.DataFrame[ExtGrid] = field(
        default_factory=lambda: ExtGrid.create_empty()
    )
    load: dy.DataFrame[Load] = field(
        default_factory=lambda: Load.create_empty()
    )
    trafo: dy.DataFrame[Trafo] = field(
        default_factory=lambda: Trafo.create_empty()
    )
    sgen: dy.DataFrame[Sgen] = field(
        default_factory=lambda: Sgen.create_empty()
    )

    def __post_init__(self):
        validate(**self.__dict__)

    def _replace(self, **kwargs: Unpack[PandaPowerDataFrame]):
        validate(**kwargs)
        return replace(self, **kwargs)

    def _cast_and_validate(
        self, table: pl.DataFrame, table_name: str
    ):
        # Cast the new table to the schema
        try:

            schema = all_models[table_name]

            new_df: pl.DataFrame = table.select(
                pl.col(col) if col in table.columns else pl.lit(None).alias(col)
                for col in schema.column_names()
            )
            new_df: pl.DataFrame = schema.cast(new_df)

            # Fill null values with default values if specified in the schema
            new_df: pl.DataFrame = new_df.with_columns(
                c.col.fill_null(value=c.metadata["default"])
                for _, c in schema.columns().items()
                if c.metadata is not None and "default" in c.metadata
            )
        
        except dy.exc.SchemaError as error: # type: ignore  
            raise ValueError(f"\n\n\nSchema error for table {table_name} with error: {error}")
        except pl.exceptions.InvalidOperationError as error:
            raise ValueError(f"\n\n\nInvalid operation error for table {table_name} with error: {error}")
        return new_df

    def replace_table(self, **kwargs: Unpack[PandaPowerDataFrame]):
        table_dict: dict[str, pl.DataFrame] = {}
        for table_name, table in kwargs.items():
            table_dict[table_name] = self._cast_and_validate(
                table=table, table_name=table_name
            )
        return self._replace(**table_dict)

    
    def schema_to_pandapower(self) -> pp.pandapowerNet:
        net: pp.pandapowerNet = pp.create_empty_network()
        for table_name, table_pl in self.__dict__.items():
            net[table_name] = pl.DataFrame(table_pl).to_pandas().set_index("id")
        return net
    
    def read_excel(self, file_path: str) -> pp.pandapowerNet:
        data_dict = {}

        for eq_name in openpyxl.load_workbook(file_path).sheetnames:
            if eq_name not in self.__dict__.keys():
                continue
            try:
                logging.getLogger("fastexcel").setLevel(logging.ERROR)
                # or, if it doesn't work, try silencing the root logger for that call:
                logging.disable(logging.WARNING)
                data_dict[eq_name] = pl.read_excel(file_path, sheet_name=eq_name)
                if eq_name != "bus":
                    data_dict[eq_name] = data_dict[eq_name].with_row_index(name="id")
            except Exception as e:
                raise ValueError(
                    f"\n\n\nFailed to read table {eq_name} from Excel file with error: {e}"
                )
        
        return self.replace_table(**data_dict).schema_to_pandapower()