{% set name = "click" %}
{% set version = "8.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ca9853ad459e787e2192211578cc907e7594e294c7ccc834310722b41b9ca6de

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - colorama   # [ win ]
    - importlib-metadata   # [ py < 38 ]
    - pip
    - python
  run:
    - colorama   # [ win ]
    - importlib-metadata   # [ py < 38 ]
    - python

about:
  home: The package home page
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Composable command line interface toolkit"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - luca-tomasini
